# Generated by Django 4.2.27 on 2026-02-26 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HouseManagement', '0010_alter_houseimages_images'),
        ('Payment', '0002_alter_payments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HouseManagement.house'),
        ),
        migrations.CreateModel(
            name='SavedNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_numbers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
