# Generated by Django 4.2.27 on 2026-02-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseManagement', '0004_remove_agent_user_agent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalfeatures',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housefeatureassignment',
            name='custom_feature_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
