# Generated by Django 4.2.27 on 2026-02-16 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HouseManagement', '0005_additionalfeatures_is_custom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='agent',
        ),
        migrations.AddField(
            model_name='house',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_houses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
