# Generated by Django 4.2.27 on 2026-02-17 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HouseManagement', '0006_remove_house_agent_house_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_houses', to=settings.AUTH_USER_MODEL),
        ),
    ]
