# Generated by Django 4.2.27 on 2026-02-17 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HouseManagement', '0007_alter_house_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='houses', to='HouseManagement.agent'),
        ),
    ]
