# Generated by Django 4.2.27 on 2026-02-22 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HouseManagement', '0008_house_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housefeatureassignment',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_assignments', to='HouseManagement.additionalfeatures'),
        ),
    ]
