# Generated by Django 4.2.27 on 2026-02-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseManagement', '0009_alter_housefeatureassignment_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimages',
            name='images',
            field=models.ImageField(upload_to='Houses/house_images/'),
        ),
    ]
